git-debimport cryptsetup_1.4.3-4.debian.tar.gz

diff --git a/debian/initramfs/cryptgnupg-hook b/debian/initramfs/cryptgnupg-hook
--- a/debian/initramfs/cryptgnupg-hook
+++ b/debian/initramfs/cryptgnupg-hook
@@ -30,11 +30,12 @@ keys=$(sed 's/^\(.*,\|\)key=//; s/,.*//' ${DESTDIR}/conf/conf.d/cryptroot)
 
 if [ "${keys}" != "none" ]; then
     if [ -z "${keys}" ]; then
-        echo $0: Missing key files in ${DESTDIR}/conf/conf.d/cryptroot >&2
+        echo "$0: Missing key files in ${DESTDIR}/conf/conf.d/cryptroot" >&2
         cat ${DESTDIR}/conf/conf.d/cryptroot >&2
         exit 1
     fi
     for key in ${keys} ; do
+	echo "WARNING: GnuPG key $key is copied to initramfs" >&2
         if [ ! -d ${DESTDIR}/$(dirname ${key}) ] ; then
             mkdir -p ${DESTDIR}/$(dirname ${key})
         fi
diff --git a/debian/initramfs/cryptroot-hook b/debian/initramfs/cryptroot-hook
--- a/debian/initramfs/cryptroot-hook
+++ b/debian/initramfs/cryptroot-hook
@@ -77,6 +77,9 @@ get_resume_devices() {
 	devices=""
 	count=0
 	for device in $candidates; do
+		# Remove quotes around device candidate
+		device=$(echo $device | sed -e 's/^"\(.*\)"[[:space:]]*$/\1/' -e "s/^'\(.*\)'[[:space:]]*$/\1/")
+
 		# Weed out clever defaults
 		if [ "$device" = "<path_to_resume_device_file>" ]; then
 			continue
@@ -86,7 +89,10 @@ get_resume_devices() {
 		derived="$(grep "^${device#/dev/mapper/}\b.*decrypt_derived" /etc/crypttab 2>/dev/null | awk '{print $3}')"
 		if [ -n "$derived" ]; then
 			if grep -q "^$derived" /etc/crypttab; then
-				candidates="$candidates /dev/mapper/$derived"
+				derived=$(canonical_device "/dev/mapper/$derived") || return 0
+				if [ "$derived" != "$rootdev" ]; then
+					devices="$devices $derived"
+				fi
 			else
 				echo "cryptsetup: WARNING: decrypt_derived device $derived not found in crypttab" >&2
 			fi
@@ -141,20 +147,18 @@ get_lvm_deps() {
 		return 1
 	fi
 
-	if ! deps=$(dmsetup deps "$node" 2> /dev/null | sed 's/[^:]*: *//;s/[ (]//g;s/)/ /g'); then
-		echo "cryptsetup: WARNING: failed to find deps for $node" >&2
-		return 1
+	if ! deps=$(vgs --noheadings -o pv_name $(dmsetup --noheadings splitname $node | cut -d':' -f1) 2>/dev/null); then
+		# $node is not a LVM node, stopping here
+		return 0
 	fi
 
-	# We should now have a list of major,minor pairs, e.g. "3,2 3,3"
+	# We should now have a list physical volumes for the VG
 	for dep in $deps; do
-		maj=$(echo ${dep%,*} | sed -e "s/^[ \t]*//g")
-		min=$(echo ${dep#*,} | sed -e "s/[ \t]*$//g")
-		depnode=$(dmsetup ls | sed -n "s/\\([^ ]*\\) *($maj, $min)/\\1/p" | sed -e "s/[ \t]*$//")
+		depnode=$(dmsetup info -c --noheadings -o name "$dep" 2>/dev/null)
 		if [ -z "$depnode" ]; then
 			continue
 		fi
-		if [ "$(dmsetup table "$depnode" 2> /dev/null | cut -d' ' -f3)" != "crypt" ]; then
+		if [ "$(dmsetup table "$depnode" 2>/dev/null | cut -d' ' -f3)" != "crypt" ]; then
 			get_lvm_deps "$depnode"
 			continue
 		fi
@@ -182,7 +186,7 @@ get_device_opts() {
 	rootopts=$( echo $opt | cut -d " " -f4- )
 
 	if [ -z "$opt" ] || [ -z "$source" ] || [ -z "$key" ] || [ -z "$rootopts" ]; then
-		echo "cryptsetup: WARNING: invalid line in /etc/crypttab - $opt" >&2
+		echo "cryptsetup: WARNING: invalid line in /etc/crypttab for $target - $opt" >&2
 		return 1
 	fi
 
@@ -243,6 +247,9 @@ get_device_opts() {
 				OPTIONS="$OPTIONS,$opt"
 				;;
 			rootdev)
+				OPTIONS="$OPTIONS,$opt"
+				;;
+			discard)
 				OPTIONS="$OPTIONS,$opt"
 				;;
 			luks)
@@ -392,7 +399,7 @@ add_device() {
 		if ! get_device_opts "$node" "$opts"; then
 			continue
 		fi
-		echo "$OPTIONS" >> "$DESTDIR/conf/conf.d/cryptroot"
+		echo "$OPTIONS" >>"$DESTDIR/conf/conf.d/cryptroot"
 
 		# If we have a keyscript, make sure it is included
 		if [ -n "$KEYSCRIPT" ]; then
@@ -404,6 +411,10 @@ add_device() {
 				copy_exec "/lib/cryptsetup/scripts/$KEYSCRIPT" /lib/cryptsetup/scripts >&2
 			elif [ -e "$KEYSCRIPT" ]; then
 				copy_exec "$KEYSCRIPT" /lib/cryptsetup/scripts >&2
+			elif KSTYPE="$(type "$KEYSCRIPT" 2>&1)"; then
+				if [ -x "${KSTYPE#"$KEYSCRIPT" is }" ]; then
+					copy_exec "${KSTYPE#"$KEYSCRIPT" is }" /lib/cryptsetup/scripts >&2
+				fi
 			else
 				echo "cryptsetup: WARNING: failed to find keyscript $KEYSCRIPT" >&2
 				continue
@@ -419,11 +430,18 @@ add_device() {
 		echo dm_mod
 		echo dm_crypt
 		echo "$modules"
-
+		# Load hardware aes module
+		if cpu_has_aesni; then
+			echo aesni
+		fi
 		i=$(( $i + 1 ))
 	done
 
 	return 0
+}
+
+cpu_has_aesni() {
+	return $(grep -q aes /proc/cpuinfo)
 }
 
 add_crypto_modules() {
@@ -446,14 +464,14 @@ add_crypto_modules() {
 	#
 	#   d) /lib/modules/$VERSION/kernel/drivers/crypto/$specific-$mod.ko
 
-	for file in $(find "$MODULESDIR/kernel/arch/" -name "$mod-*.ko"); do
+	for file in $(find "$MODULESDIR/kernel/arch/" -name "$mod-*.ko" 2>/dev/null); do
 		altmod="${file##*/}"
 		altmod="${altmod%.ko}"
 		manual_add_modules "$altmod"
 		found="yes"
 	done
 
-	for file in $(find "$MODULESDIR/kernel/crypto/" -name "${mod}_generic.ko"); do
+	for file in $(find "$MODULESDIR/kernel/crypto/" -name "${mod}_generic.ko" 2>/dev/null); do
 		altmod="${file##*/}"
 		altmod="${altmod%.ko}"
 		manual_add_modules "$altmod"
@@ -462,7 +480,7 @@ add_crypto_modules() {
 	done
 
 	if [ -z "$genericfound" ]; then
-		for file in $(find "$MODULESDIR/kernel/crypto/" -name "${mod}.ko"); do
+		for file in $(find "$MODULESDIR/kernel/crypto/" -name "${mod}.ko" 2>/dev/null); do
 			altmod="${file##*/}"
 			altmod="${altmod%.ko}"
 			manual_add_modules "$altmod"
@@ -503,7 +521,7 @@ for dev in $rootdev $resumedevs; do
 	setup="yes"
 
 	if [ "$MODULES" = "most" ]; then
-		archcrypto="$(find "$MODULESDIR/kernel/arch" -type d -name "crypto")"
+		archcrypto="$(find "$MODULESDIR/kernel/arch" -type d -name "crypto" 2>/dev/null)"
 		if [ -n "$archcrypto" ]; then
 			copy_modules_dir "${archcrypto##*${MODULESDIR}/}"
 		fi
@@ -531,6 +549,11 @@ if [ "$MODULES" != "dep" ] || [ "$setup" = "yes" ]; then
 	copy_exec /sbin/cryptsetup
 	copy_exec /sbin/dmsetup
 	copy_exec /lib/cryptsetup/askpass
+
+	# We need sed. Either via busybox or as standalone binary.
+	if [ "$BUSYBOX" = "n" ] || [ ! -e ${BUSYBOXDIR}/busybox ]; then
+		copy_exec /bin/sed
+	fi
 fi
 
 exit 0
diff --git a/debian/initramfs/cryptroot-script b/debian/initramfs/cryptroot-script
--- a/debian/initramfs/cryptroot-script
+++ b/debian/initramfs/cryptroot-script
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+PREREQ="cryptroot-prepare"
+
 #
 # Standard initramfs preamble
 #
@@ -31,8 +33,6 @@ message()
 {
 	if [ -x /bin/plymouth ] && plymouth --ping; then
 		plymouth message --text="$@"
-	elif [ -p /dev/.initramfs/usplash_outfifo ] && [ -x /sbin/usplash_write ]; then
-		usplash_write "TEXT-URGENT $@"
 	else
 		echo "$@" >&2
 	fi
@@ -70,6 +70,7 @@ parse_options()
 	cryptkey="" # This is only used as an argument to an eventual keyscript
 	crypttries=3
 	cryptrootdev=""
+	cryptdiscard=""
 	CRYPTTAB_OPTIONS=""
 
 	local IFS=" ,"
@@ -120,6 +121,9 @@ parse_options()
 		rootdev)
 			cryptrootdev="yes"
 			;;
+		discard)
+			cryptdiscard="yes"
+			;;
 		esac
 		PARAM="${x%=*}"
 		if [ "$PARAM" = "$x" ]; then
@@ -149,7 +153,7 @@ activate_vg()
 
 	# Detect and activate available volume groups
 	/sbin/lvm vgscan
-	/sbin/lvm vgchange -ay
+	/sbin/lvm vgchange -a y --sysinit
 	return $?
 }
 
@@ -184,7 +188,7 @@ setup_mapping()
 
 	parse_options "$opts" || return 1
 
-	if [ -n "$cryptkeyscript" ] && [ ! -x "$cryptkeyscript" ]; then
+	if [ -n "$cryptkeyscript" ] && ! type "$cryptkeyscript" >/dev/null; then
 		message "cryptsetup: error - script \"$cryptkeyscript\" missing"
 		return 1
 	fi
@@ -218,9 +222,6 @@ setup_mapping()
 		else
 			slumber=${ROOTDELAY}
 		fi
-		if [ -x /sbin/usplash_write ]; then
-			/sbin/usplash_write "TIMEOUT ${slumber}" || true
-		fi
 
 		slumber=$(( ${slumber} * 10 ))
 		while [ ! -e "$cryptsource" ]; do
@@ -234,24 +235,25 @@ setup_mapping()
 		else
 			log_end_msg 1 || true
 		fi
-		if [ -x /sbin/usplash_write ]; then
-			/sbin/usplash_write "TIMEOUT 15" || true
-		fi
  	fi
 	udev_settle
 
 	# We've given up, but we'll let the user fix matters if they can
 	while [ ! -e "${cryptsource}" ]; do
-		echo "	Check cryptopts=source= bootarg cat /proc/cmdline"
-		echo "	or missing modules, devices: cat /proc/modules ls /dev"
+		echo "	Check cryptopts=source= bootarg: cat /proc/cmdline"
+		echo "	or missing modules, devices: cat /proc/modules; ls /dev"
 		panic -r "ALERT!  ${cryptsource} does not exist.  Dropping to a shell!"
 	done
 
 	# Prepare commands
-	if /sbin/cryptsetup isLuks $cryptsource > /dev/null 2>&1; then
-		cryptcreate="/sbin/cryptsetup -T 1 luksOpen $cryptsource $crypttarget"
+	cryptcreate="/sbin/cryptsetup -T 1"
+	if [ "$cryptdiscard" = "yes" ]; then
+		cryptcreate="$cryptcreate --allow-discards"
+	fi
+	if /sbin/cryptsetup isLuks $cryptsource >/dev/null 2>&1; then
+		cryptcreate="$cryptcreate luksOpen $cryptsource $crypttarget"
 	else
-		cryptcreate="/sbin/cryptsetup -T 1 -c $cryptcipher -s $cryptsize -h $crypthash create $crypttarget $cryptsource"
+		cryptcreate="$cryptcreate -c $cryptcipher -s $cryptsize -h $crypthash create $crypttarget $cryptsource"
 	fi
 	cryptremove="/sbin/cryptsetup remove $crypttarget"
 	NEWROOT="/dev/mapper/$crypttarget"
@@ -265,26 +267,23 @@ setup_mapping()
 			/bin/sleep 3
 		fi
 
-		if [ $crypttries -gt 0 ] && [ $count -gt $crypttries ]; then
-			message "cryptsetup: maximum number of tries exceeded for $crypttarget"
-			return 1
-		fi
-
 		if [ -z "$cryptkeyscript" ]; then
 			cryptkey="Unlocking the disk $cryptsource ($crypttarget)\nEnter passphrase: "
 			if [ -x /bin/plymouth ] && plymouth --ping; then
 				cryptkeyscript="plymouth ask-for-password --prompt"
-				cryptkey=$(echo -e "$cryptkey")
+				cryptkey=$(printf "$cryptkey")
 			else
 				cryptkeyscript="/lib/cryptsetup/askpass"
 			fi
 		fi
 
 
-		if ! crypttarget="$crypttarget" cryptsource="$cryptsource" \
-		     $cryptkeyscript "$cryptkey" | $cryptcreate --key-file=- ; then
-			message "cryptsetup: cryptsetup failed, bad password or options?"
-			continue
+		if [ ! -e "$NEWROOT" ]; then
+			if ! crypttarget="$crypttarget" cryptsource="$cryptsource" \
+			     $cryptkeyscript "$cryptkey" | $cryptcreate --key-file=- ; then
+				message "cryptsetup: cryptsetup failed, bad password or options?"
+				continue
+			fi
 		fi
 
 		if [ ! -e "$NEWROOT" ]; then
@@ -292,11 +291,13 @@ setup_mapping()
 			return 1
 		fi
 
-		FSTYPE=''
-		eval $(fstype < "$NEWROOT")
+		#FSTYPE=''
+		#eval $(fstype < "$NEWROOT")
+		FSTYPE="$(blkid -s TYPE -o value "$NEWROOT")"
 
 		# See if we need to setup lvm on the crypto device
-		if [ "$FSTYPE" = "lvm" ] || [ "$FSTYPE" = "lvm2" ]; then
+		#if [ "$FSTYPE" = "lvm" ] || [ "$FSTYPE" = "lvm2" ]; then
+		if [ "$FSTYPE" = "LVM_member" ] || [ "$FSTYPE" = "LVM2_member" ]; then
 			if [ -z "$cryptlvm" ]; then
 				message "cryptsetup: lvm fs found but no lvm configured"
 				return 1
@@ -306,15 +307,16 @@ setup_mapping()
 				return 1
 			fi
 
-			NEWROOT="/dev/mapper/$cryptlvm"
+			NEWROOT=${cmdline_root:-/dev/mapper/$cryptlvm}
 			if [ "$cryptrootdev" = "yes" ]; then
 				# required for lilo to find the root device
-				echo "ROOT=$NEWROOT" >> /conf/param.conf
+				echo "ROOT=$NEWROOT" >>/conf/param.conf
 			fi
 			eval $(fstype < "$NEWROOT")
 		fi
 
-		if [ -z "$FSTYPE" ] || [ "$FSTYPE" = "unknown" ]; then
+		#if [ -z "$FSTYPE" ] || [ "$FSTYPE" = "unknown" ]; then
+		if [ -z "$FSTYPE" ]; then
 			message "cryptsetup: unknown fstype, bad password or options?"
 			udev_settle
 			$cryptremove
@@ -325,6 +327,11 @@ setup_mapping()
 		break
 	done
 
+	if [ $crypttries -gt 0 ] && [ $count -gt $crypttries ]; then
+		message "cryptsetup: maximum number of tries exceeded for $crypttarget"
+		return 1
+	fi
+
 	udev_settle
 	return 0
 }
@@ -334,17 +341,37 @@ setup_mapping()
 #
 
 # Do we have any kernel boot arguments?
-found=''
+cmdline_cryptopts=''
+unset cmdline_root
 for opt in $(cat /proc/cmdline); do
 	case $opt in
 	cryptopts=*)
-		found=yes
-		setup_mapping "${opt#cryptopts=}"
+		opt="${opt#cryptopts=}"
+		if [ -n "$opt" ]; then
+			if [ -n "$cmdline_cryptopts" ]; then
+				cmdline_cryptopts="$cmdline_cryptopts $opt"
+			else
+				cmdline_cryptopts="$opt"
+			fi
+		fi
+		;;
+	root=*)
+		opt="${opt#root=}"
+		case $opt in
+		/*) # Absolute path given. Not lilo major/minor number.
+			cmdline_root=$opt
+			;;
+		*) # lilo major/minor number (See #398957). Ignore
+		esac
 		;;
 	esac
 done
 
-if [ -n "$found" ]; then
+if [ -n "$cmdline_cryptopts" ]; then
+	# Call setup_mapping separately for each possible cryptopts= setting
+	for cryptopt in $cmdline_cryptopts; do
+		setup_mapping "$cryptopt"
+	done
 	exit 0
 fi
 
